#!/bin/sh

set -e

# Clean up.
CURRENT_PATH=$(dirname "$0")
. ${CURRENT_PATH}/clean.sh

# Generate proto code.
python3 -m grpc_tools.protoc \
  -I=. \
  --python_out=./src/python_grpc \
  --grpc_python_out=./src/python_grpc \
  ./google/api/http.proto ./google/api/annotations.proto \
  ./proto/unary.proto

protoc \
  -I=. \
  --go_out ./src/go_rest_proxy/autogenerated/ --go_opt paths=source_relative \
  --go-grpc_out ./src/go_rest_proxy/autogenerated/ --go-grpc_opt paths=source_relative \
  --grpc-gateway_out ./src/go_rest_proxy/autogenerated/ \
  --grpc-gateway_opt logtostderr=true \
  --grpc-gateway_opt paths=source_relative \
  ./proto/unary.proto

# Generate Go modules.
cd src/go_rest_proxy/autogenerated/proto/
go mod init github.com/thiagorobert/space-api/autogenerated_proto
go mod tidy
cd -

go mod init github.com/thiagorobert/space-api
echo "replace github.com/thiagorobert/space-api/autogenerated_proto => ./src/go_rest_proxy/autogenerated/proto/" >> go.mod
go mod tidy -compat=1.17

# Build Go binary.
go build src/go_rest_proxy/rest_reverse_proxy.go
