#!/bin/sh

set -e

rm -rf src/go_rest_proxy/autogenerated/*
rm -rf src/python_grpc/proto
rm -rf src/python_grpc/google
rm -f go.mod go.sum
rm -f rest_reverse_proxy
for I in `find src/python_grpc/ | grep __pycache__`; do
  rm -rf $I
done
